FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

COPY worker ./worker
COPY src ./src
COPY tsconfig.json ./

CMD ["npx", "tsx", "worker/index.ts"]
