FROM node:20.19-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm ci --legacy-peer-deps --ignore-scripts
RUN npx prisma generate

COPY worker ./worker
COPY src ./src
COPY scripts ./scripts
COPY tsconfig.json ./

CMD ["npx", "tsx", "worker/index.ts"]
