FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci --legacy-peer-deps

COPY worker ./worker
COPY src ./src
COPY scripts ./scripts
COPY tsconfig.json ./

CMD ["npx", "tsx", "worker/index.ts"]
