@echo off
REM Generated by project-control-heim/scripts/install_agent_rules.py — do not edit.
REM Locates project-control-heim, then runs the shared hook. Fails OPEN.
setlocal EnableExtensions

set "HERE=%~dp0"
REM hooks dir is <repo>/.cursor/hooks → repo root is ../..
for %%I in ("%HERE%..\..") do set "REPO_ROOT=%%~fI"

set "PC=%PROJECT_CONTROL%"
if "%PC%"=="" if exist "%REPO_ROOT%\..\project-control-heim\" (
  for %%I in ("%REPO_ROOT%\..\project-control-heim") do set "PC=%%~fI"
)
if "%PC%"=="" set "PC=D:\Dev\Projects\project-control-heim"

set "PY="
where python >nul 2>&1 && set "PY=python"
if not defined PY where python3 >nul 2>&1 && set "PY=python3"
if not defined PY (
  echo {}
  exit /b 0
)
if not exist "%PC%\scripts\hooks\guard_writes.py" (
  echo {}
  exit /b 0
)

REM Consume stdin (hook payload) via python reading sys.stdin
"%PY%" "%PC%\scripts\hooks\guard_writes.py" "homebase" "%REPO_ROOT%"
exit /b %ERRORLEVEL%
