#!/usr/bin/env bash
# Generated by project-control-heim/scripts/install_agent_rules.py — do not edit.
# Locates project-control-heim, then runs the shared hook. Fails OPEN: if anything
# is missing this prints "{}" and exits 0 so your session is never blocked.
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

# 1. explicit override  2. sibling of this repo  3. path captured at install time
PC="${PROJECT_CONTROL:-}"
if [ -z "$PC" ] && [ -d "$REPO_ROOT/../project-control-heim" ]; then
  PC="$(cd "$REPO_ROOT/../project-control-heim" && pwd)"
fi
if [ -z "$PC" ] || [ ! -d "$PC" ]; then
  PC="D:\Dev\Projects\project-control-heim"
fi

PY="$(command -v python3 || command -v python || true)"
if [ -z "$PY" ] || [ ! -f "$PC/scripts/hooks/guard_writes.py" ]; then
  cat > /dev/null
  echo '{}'
  exit 0
fi

exec "$PY" "$PC/scripts/hooks/guard_writes.py" "homebase" "$REPO_ROOT"
